export const DiscoverIdeasList = [
  {
    id: 1,
    title: "Trending Places",
    desc: "Explore trending spots globally",
    tripCategory: "TRENDING",
    route: "/discover-trip/trending",
    image: require("../../assets/images/discover/trending.png"),
  },
  {
    id: 2,
    title: "Hidden Gems",
    desc: "Discover underrated and offbeat destinations",
    tripCategory: "HIDDEN",
    route: "/discover-trip/hidden-gems",
    image: require("../../assets/images/discover/hidden_gems.webp"),
  },
  {
    id: 3,
    title: "Concert Nights",
    desc: "Catch your favorite artists live",
    route: "/discover-trip/concert-trips/select-artist",
    image: require("../../assets/images/discover/concert.jpg"),
  },
  {
    id: 4,
    title: "Festive Getaways",
    desc: "Trips during local or global festivals",
    tripCategory: "FESTIVE",
    route: "/discover-trip/festive",
    image: require("../../assets/images/discover/festive.jpg"),
  },
];

export const POPULAR_COUNTRIES_LIST = [
  { name: "Japan", label: "🇯🇵 Japan" },
  { name: "United States", label: "🇺🇸 United States" },
  { name: "Italy", label: "🇮🇹 Italy" },
  { name: "UAE", label: "🇦🇪 UAE" },
  { name: "Thailand", label: "🇹🇭 Thailand" },
  { name: "France", label: "🇫🇷 France" },
  { name: "Indonesia", label: "🇮🇩 Indonesia" },
];

export const CITY_ALIASES: Record<string, string> = {
  "london": "London",
  "mumbai city": "Mumbai",
  "bombay": "Mumbai",
  "new york city": "New York",
  "bengaluru urban": "Bengaluru",
};

export const STORAGE_KEYS = {
  HOME_COUNTRY: "USER_HOME_COUNTRY",
  SELECTED_COUNTRY: "USER_SELECTED_COUNTRY",
};

export const SUGGESTED_OUTBOUND: Record<string, string[]> = {
  US: ["Japan", "Italy", "France", "India", "United Kingdom"],
  IN: ["Japan", "United States", "Thailand", "Vietnam", "UAE"],
  DEFAULT: ["United States", "Japan", "Italy", "France", "Thailand"],
};

export const BACKUPS = ["United Kingdom", "Spain", "Singapore"];

export const COUNTRY_EMOJIS: Record<string, string> = {
  "India": "🇮🇳",
  "United States": "🇺🇸",
  "Japan": "🇯🇵",
  "Italy": "🇮🇹",
  "UAE": "🇦🇪",
  "Thailand": "🇹🇭",
  "France": "🇫🇷",
  "Indonesia": "🇮🇩",
  "United Kingdom": "🇬🇧",
  "UK": "🇬🇧",
  "Vietnam": "🇻🇳",
  "Spain": "🇪🇸",
  "Singapore": "🇸🇬",
};

export const FestiveTripIdeas = [
  {
    id: 1,
    name: "Varanasi",
    title: "Varanasi, India",
    country: "India",
    countryCode: "in",
    festival: "Diwali – Festival of Lights",
    Highlights: "Ganga Aarti, thousands of diyas & spiritual rituals",
    insight: "Diwali in Varanasi commemorates Lord Rama's triumphant return. The ghats are illuminated with millions of earthen lamps to guide him home, creating a breathtaking celestial reflection on the Ganges.",
    auspiciousDay: "Nov 1",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718275/diwali_trtgol.jpg",
  },
  {
    id: 2,
    name: "Mecca",
    title: "Mecca, Saudi Arabia",
    country: "Saudi Arabia",
    countryCode: "sa",
    festival: "Hajj & Eid al-Adha",
    Highlights: "Spiritual pilgrimage and Kaaba rituals",
    insight: "Hajj is a mandatory spiritual journey that symbolizes universal equality. It represents a profound submission to the divine, bringing together millions of seekers from every corner of the globe.",
    auspiciousDay: "Varies (May/June)",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718278/mecca_tamv55.jpg",
  },
  {
    id: 3,
    name: "Jerusalem",
    title: "Jerusalem, Israel",
    country: "Israel",
    countryCode: "il",
    festival: "Easter & Passover",
    Highlights: "Holy Sepulchre, Western Wall & religious convergence",
    insight: "Jerusalem hosts a profound convergence of Easter and Passover celebrations. It marks the sacred heart of multiple global faiths, where ancient traditions and shared history meet.",
    auspiciousDay: "Varies (March/April)",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718277/jerusalem_oihxca.jpg",
  },
  {
    id: 4,
    name: "Amritsar",
    title: "Amritsar, India",
    country: "India",
    countryCode: "in",
    festival: "Gurpurab",
    Highlights: "Golden Temple illuminations & kirtans",
    insight: "Gurpurab celebrates the birth of Guru Nanak. On this day, the Golden Temple is transformed into a sanctuary of selfless service, peace, and radiant divine light.",
    auspiciousDay: "Nov 25",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718275/amritsar_cyp5dk.jpg",
  },
  {
    id: 5,
    name: "Kathmandu",
    title: "Kathmandu, Nepal",
    country: "Nepal",
    countryCode: "np",
    festival: "Buddha Jayanti",
    Highlights: "Boudhanath prayers, butter lamps & Buddhist energy",
    insight: "Buddha Jayanti honors the birth, enlightenment, and nirvana of Lord Buddha. The majestic Stupas of Swayambhunath and Boudhanath are filled with prayers and the soft glow of butter lamps.",
    auspiciousDay: "May 1",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718277/kathmandu_yiguhm.jpg",
  },
  {
    id: 6,
    name: "Rio de Janeiro",
    title: "Rio de Janeiro, Brazil",
    country: "Brazil",
    countryCode: "br",
    festival: "Christmas + New Year",
    Highlights: "Copacabana fireworks & beachside masses",
    insight: "Rio's New Year is a global spectacle of renewal and joy. Millions of white-clad celebrants gather on Copacabana beach to offer flowers to the sea under a sky of magnificent fireworks.",
    auspiciousDay: "Dec 25",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718285/rio_sa46hq.jpg",
  },
  {
    id: 7,
    name: "Pushkar",
    title: "Pushkar, India",
    country: "India",
    countryCode: "in",
    festival: "Kartik Purnima",
    Highlights: "Cultural fair and spiritual rituals at the lake",
    insight: "Kartik Purnima marks the creation of Pushkar Lake by Lord Brahma. It is a sacred day of spiritual cleansing and vibrant cultural celebration in the heart of the Rajasthan desert.",
    auspiciousDay: "Nov 24",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718281/pushkar_abaonb.jpg",
  },
  {
    id: 8,
    name: "Bangkok",
    title: "Bangkok, Thailand",
    country: "Thailand",
    countryCode: "th",
    festival: "Songkran – Thai New Year",
    Highlights: "Fun water fights and Buddhist temple blessings",
    insight: "Songkran is the traditional Thai New Year. It is a joyful celebration of renewal where water is used to wash away the old and usher in fresh blessings for the coming year.",
    auspiciousDay: "April 13-15",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718290/songkran_poox1w.jpg",
  },
  {
    id: 9,
    name: "Lourdes",
    title: "Lourdes, France",
    country: "France",
    countryCode: "fr",
    festival: "Feast of the Assumption",
    Highlights: "Torchlight processions and healing masses",
    insight: "The Feast of the Assumption is a major day of Catholic pilgrimage. It honors the Virgin Mary and centers around the sacred grotto where miraculous healings and spiritual strength are sought.",
    auspiciousDay: "Aug 15",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718274/assumption-day_icpka2.jpg",
  },
  {
    id: 10,
    name: "Bali",
    title: "Bali, Indonesia",
    country: "Indonesia",
    countryCode: "id",
    festival: "Nyepi – Day of Silence",
    Highlights: "Unique silence rituals and Ogoh-Ogoh parades",
    insight: "Nyepi is Bali's unique Day of Silence. It is a day dedicated to meditation and self-reflection, when the entire island comes to a standstill to cleanse the spirit and restore natural balance.",
    auspiciousDay: "March",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718285/nyepi_dczj6j.jpg",
  },
  {
    id: 11,
    name: "Mexico City",
    title: "Mexico City, Mexico",
    country: "Mexico",
    countryCode: "mx",
    festival: "Day of the Dead",
    Highlights: "Ofrendas, calaveras and soulful remembrance",
    insight: "The Day of the Dead is a beautiful and soulful remembrance. Families use vibrant ofrendas and marigold paths to guide the spirits of their loved ones back for a night of shared celebration.",
    auspiciousDay: "Nov 2",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718300/mexico_q7r2g0.jpg",
  },
  {
    id: 12,
    name: "Kyoto",
    title: "Kyoto, Japan",
    country: "Japan",
    countryCode: "jp",
    festival: "Cherry Blossom (Hanami)",
    Highlights: "Sakura blooms and traditional tea rituals",
    insight: "Hanami is the ancient Japanese tradition of cherry blossom viewing. It celebrates the fleeting beauty of life and the arrival of spring under the breathtaking canopy of Sakura trees.",
    auspiciousDay: "April",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718311/kyoto_ps7smo.jpg",
  },
  {
    id: 13,
    name: "Munich",
    title: "Munich, Germany",
    country: "Germany",
    countryCode: "de",
    festival: "Oktoberfest",
    Highlights: "Bavarian culture, beer tents and parades",
    insight: "Oktoberfest is the world's largest celebration of Bavarian culture. It is a joyful festival that highlights shared community spirit, traditional heritage, and world-renowned hospitality.",
    auspiciousDay: "Sept / Oct",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718286/munich_zrej65.jpg",
  },
  {
    id: 14,
    name: "Venice",
    title: "Venice, Italy",
    country: "Italy",
    countryCode: "it",
    festival: "Venice Carnival",
    Highlights: "Masquerade masks and mysterious elegance",
    insight: "The Venice Carnival is an explosion of mysterious elegance and artistic flair. Iconic masquerade masks allow participants to escape into a temporary world of historical fantasy and beauty.",
    auspiciousDay: "February",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718303/venice_nfivvn.jpg",
  },
  {
    id: 15,
    name: "Seville",
    title: "Seville, Spain",
    country: "Spain",
    countryCode: "es",
    festival: "Semana Santa",
    Highlights: "Intense devotion and processional floats",
    insight: "Semana Santa is an intense and moving display of devotion. Magnificent processional floats move through historic streets, showcasing centuries of tradition and masterful artistry.",
    auspiciousDay: "April",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718309/seville_ppeklx.jpg",
  },
];

export const HiddenGemIdeas = [
  {
    id: 1,
    name: "Tawang",
    title: "Tawang, Arunachal Pradesh",
    country: "India",
    countryCode: "in",
    desc: "Explore serene monasteries and Himalayan landscapes in this remote gem.",
    insight: "A high-altitude sanctuary where the world's largest Buddhist monastery stands amidst the clouds. It offers a rare and peaceful glimpse into the spiritual solitude of the Himalayas.",
    recommendedMonth: "Oct - April",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232707/tawang_ji5iiy.jpg",
  },
  {
    id: 2,
    name: "Gokarna",
    title: "Gokarna, Karnataka",
    country: "India",
    countryCode: "in",
    desc: "Unwind at peaceful beaches and ancient temples away from Goa crowds.",
    insight: "Gokarna is often called the 'untouched Goa.' It is a place where rugged sea-cliffs meet pristine beaches and ancient Shiva temples define the soul of the coastline.",
    recommendedMonth: "Oct - March",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232696/gokarna_gktdgn.jpg",
  },
  {
    id: 3,
    name: "Chopta",
    title: "Chopta, Uttarakhand",
    country: "India",
    countryCode: "in",
    desc: "Trek through alpine meadows to Tungnath, the world's highest Shiva temple.",
    insight: "Known as the 'Mini Switzerland of India,' Chopta is a trekker's paradise. It serves as the serene gateway to Tungnath, the highest Shiva temple in the world.",
    recommendedMonth: "April - Nov",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232695/chopta_grcfgg.jpg",
  },
  {
    id: 4,
    name: "Majuli",
    title: "Majuli, Assam",
    country: "India",
    countryCode: "in",
    desc: "Visit the world's largest river island with rich culture and monasteries.",
    insight: "As the world's largest river island, Majuli is a disappearing cradle of culture. It remains a serene center for Assamese Neo-Vaishnavite traditions and wetland beauty.",
    recommendedMonth: "Oct - March",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232702/majuli_ajibue.jpg",
  },
  {
    id: 5,
    name: "Halebidu",
    title: "Halebidu, Karnataka",
    country: "India",
    countryCode: "in",
    desc: "Marvel at exquisite Hoysala-era temple carvings and architecture.",
    insight: "A testament to the mastery of Hoysala architecture. Every inch of its soapstone walls is intricately carved with legendary tales of gods, celestial dancers, and wildlife.",
    recommendedMonth: "Oct - March",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232697/halebidu_kb3oya.jpg",
  },
  {
    id: 6,
    name: "Ziro Valley",
    title: "Ziro Valley, Arunachal Pradesh",
    country: "India",
    countryCode: "in",
    desc: "Experience Apatani tribal culture amidst rolling hills and rice fields.",
    insight: "A lush, high-altitude valley home to the Apatani tribe. It is famous for its unique cultural heritage, sustainable farming practices, and iconic mountain landscapes.",
    recommendedMonth: "March - Oct",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232708/ziro_valey_sexmcr.jpg",
  },
  {
    id: 7,
    name: "Mawlynnong",
    title: "Mawlynnong, Meghalaya",
    country: "India",
    countryCode: "in",
    desc: "Stroll through Asia's cleanest village and see living root bridges.",
    insight: "Celebrated as the cleanest village in Asia, Mawlynnong offers a glimpse into a harmonious lifestyle. It is a place where rainforests and living root bridges are part of daily life.",
    recommendedMonth: "Sept - May",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232704/mawlynnong_j8s0mg.jpg",
  },
  {
    id: 8,
    name: "Patan",
    title: "Patan, Gujarat",
    country: "India",
    countryCode: "in",
    desc: "Step into history at Rani ki Vav, a beautifully carved stepwell.",
    insight: "Home to the magnificent Rani ki Vav, an inverted temple stepwell of breathtaking complexity. It is a UNESCO World Heritage site reflecting deep historic and architectural mastery.",
    recommendedMonth: "Oct - March",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232704/patan_pw8wrq.jpg",
  },
  {
    id: 9,
    name: "Lepakshi",
    title: "Lepakshi, Andhra Pradesh",
    country: "India",
    countryCode: "in",
    desc: "See the hanging pillar and Vijayanagara-style murals at Veerabhadra Temple.",
    insight: "A site of mythical wonder and architectural brilliance. It is famous for its hanging pillar, a massive Nandi bull, and some of the finest Vijayanagara-era mural paintings.",
    recommendedMonth: "Sept - March",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232698/lepakshi_r99zfu.jpg",
  },
  {
    id: 10,
    name: "Chandratal",
    title: "Chandratal, Himachal Pradesh",
    country: "India",
    countryCode: "in",
    desc: "Camp by the moon-shaped lake in Spiti for a surreal high-altitude escape.",
    insight: "The 'Moon Lake' is a surreal high-altitude turquoise gem. Its still waters perfectly reflect the stark and majestic beauty of the Spiti Valley's surrounding mountain peaks.",
    recommendedMonth: "June - Sept",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232697/chandratal-lake_aisjss.jpg",
  },
  {
    id: 11,
    name: "Hampi",
    title: "Hampi, Karnataka",
    country: "India",
    countryCode: "in",
    desc: "Walk among the ruins of the Vijayanagara Empire, a UNESCO heritage site.",
    insight: "A sprawling open-air museum filled with giant boulders and magnificent ruins. It tells the story of a forgotten empire that once stood as a rival to Rome itself.",
    recommendedMonth: "Oct - March",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232697/hampi_x1s3wg.jpg",
  },
  {
    id: 12,
    name: "Velas",
    title: "Velas, Maharashtra",
    country: "India",
    countryCode: "in",
    desc: "Witness the Olive Ridley turtle festival in this peaceful Konkan village.",
    insight: "A quiet coastal village that serves as a vital conservation sanctuary. It is here that tiny Olive Ridley turtles hatch and begin their epic journey to the deep sea.",
    recommendedMonth: "Feb - April",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232708/velas_lwm1gg.jpg",
  },
  {
    id: 13,
    name: "Dzukou Valley",
    title: "Dzukou Valley, Nagaland",
    country: "India",
    countryCode: "in",
    desc: "Trek across lush valleys and seasonal flowers on the Nagaland–Manipur border.",
    insight: "A hidden eden on the border of Nagaland and Manipur. It is famous for its rolling green hills, seasonal lilies, and some of the most untouched trekking trails in India.",
    recommendedMonth: "June - Sept",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232697/dzukou_valley_jorfsl.jpg",
  },
  {
    id: 14,
    name: "Chalakudy",
    title: "Chalakudy, Kerala",
    country: "India",
    countryCode: "in",
    desc: "Discover Athirappilly Falls and lush greenery known as the 'Niagara of India'.",
    insight: "Gateway to the majestic Athirappilly Falls, often called the 'Niagara of India.' It is a place where dense rainforests meet the thunderous splendor of cascading white water.",
    recommendedMonth: "Sept - March",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232697/chalakudy_ve3xvo.jpg",
  },
  {
    id: 15,
    name: "Mandu",
    title: "Mandu, Madhya Pradesh",
    country: "India",
    countryCode: "in",
    desc: "Explore Afghan-style architecture and romantic ruins of this historic fort city.",
    insight: "An ancient city of architectural joy and romantic legends. Its Afghan-style ruins tell the poetic story of Prince Baz Bahadur and his beloved Rani Roopmati.",
    recommendedMonth: "July - March",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232703/mandu_rlj3yt.jpg",
  },
  {
    id: 16,
    name: "Khimsar",
    title: "Khimsar, Rajasthan",
    country: "India",
    countryCode: "in",
    desc: "Stay in a desert fort and experience dunes away from Jaisalmer crowds.",
    insight: "A desert oasis where ancient fort walls meet rolling sand dunes. It offers a rare experience of royal solitude and stark beauty in the heart of the Thar Desert.",
    recommendedMonth: "Oct - March",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232698/khimsar_p07v1z.jpg",
  },
  {
    id: 17,
    name: "Tirthan Valley",
    title: "Tirthan Valley, Himachal Pradesh",
    country: "India",
    countryCode: "in",
    desc: "Relax by rivers and waterfalls in a less commercialized Himalayan valley.",
    insight: "An untouched Himalayan retreat beside the crystal-clear Tirthan River. It is the perfect destination for slow travel, trout fishing, and exploring the Great Himalayan National Park.",
    recommendedMonth: "March - June",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232707/tirthan_grq1vt.jpg",
  },
  {
    id: 18,
    name: "Lonar Crater",
    title: "Lonar Crater, Maharashtra",
    country: "India",
    countryCode: "in",
    desc: "See a unique lake formed by a meteor impact over 50,000 years ago.",
    insight: "A geological wonder formed by a high-velocity meteor impact 50,000 years ago. It has created a unique salt-water lake within a massive basalt rock basin.",
    recommendedMonth: "Nov - March",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232698/lonar_hfbcp7.jpg",
  },
  {
    id: 19,
    name: "Araku Valley",
    title: "Araku Valley, Andhra Pradesh",
    country: "India",
    countryCode: "in",
    desc: "Ride the scenic train and visit tribal coffee plantations in the Eastern Ghats.",
    insight: "A scenic coffee-growing haven nestled in the Eastern Ghats. It is accessible by a breathtaking train journey that passes through 58 tunnels and over mist-covered peaks.",
    recommendedMonth: "Sept - March",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232695/araku_aa3dt9.jpg",
  },
  {
    id: 20,
    name: "Kibber",
    title: "Kibber, Himachal Pradesh",
    country: "India",
    countryCode: "in",
    desc: "Spot snow leopards and visit one of the world's highest inhabited villages.",
    insight: "One of the highest inhabited villages on Earth, set in a stark and spiritual landscape. It serves as a prime habitat for the elusive and majestic snow leopard.",
    recommendedMonth: "June - Sept",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232698/kibber_vgcilh.jpg",
  },
];

export const HiddenGemsTripImages: Record<string, string> = {
  "Tawang, Arunachal Pradesh": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232707/tawang_ji5iiy.jpg",
  "Gokarna, Karnataka": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232696/gokarna_gktdgn.jpg",
  "Chopta, Uttarakhand": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232695/chopta_grcfgg.jpg",
  "Majuli, Assam": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232702/majuli_ajibue.jpg",
  "Halebidu, Karnataka": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232697/halebidu_kb3oya.jpg",
  "Ziro Valley, Arunachal Pradesh": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232708/ziro_valey_sexmcr.jpg",
  "Mawlynnong, Meghalaya": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232704/mawlynnong_j8s0mg.jpg",
  "Patan, Gujarat": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232704/patan_pw8wrq.jpg",
  "Lepakshi, Andhra Pradesh": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232698/lepakshi_r99zfu.jpg",
  "Chandratal, Himachal Pradesh": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232697/chandratal-lake_aisjss.jpg",
  "Hampi, Karnataka": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232697/hampi_x1s3wg.jpg",
  "Velas, Maharashtra": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232708/velas_lwm1gg.jpg",
  "Dzukou Valley, Nagaland": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232697/dzukou_valley_jorfsl.jpg",
  "Chalakudy, Kerala": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232697/chalakudy_ve3xvo.jpg",
  "Mandu, Madhya Pradesh": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232703/mandu_rlj3yt.jpg",
  "Khimsar, Rajasthan": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232698/khimsar_p07v1z.jpg",
  "Tirthan Valley, Himachal Pradesh": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232707/tirthan_grq1vt.jpg",
  "Lonar Crater, Maharashtra": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232698/lonar_hfbcp7.jpg",
  "Araku Valley, Andhra Pradesh": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232695/araku_aa3dt9.jpg",
  "Kibber, Himachal Pradesh": "https://res.cloudinary.com/dbjgmxt8h/image/upload/v1766232698/kibber_vgcilh.jpg",
};

export const singerOptions = [
  { id: 1, title: "Taylor Swift", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717768/taylor-swift_n4yz5f.jpg" },
  { id: 2, title: "The Weeknd", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717769/weeknd_dn53lg.jpg" },
  { id: 3, title: "Coldplay", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717756/coldplay_lggbzl.jpg" },
  { id: 4, title: "BTS", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717754/bts_av2br0.jpg" },
  { id: 5, title: "Billie Eilish", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717754/billie_oua6zw.jpg" },
  { id: 6, title: "Dua Lipa", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717757/dua_iqhgoj.jpg" },
  { id: 7, title: "Olivia Rodrigo", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717763/olivia_olwhfk.webp" },
  { id: 8, title: "Post Malone", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717769/post-malone_kuau3e.jpg" },
  { id: 9, title: "Ed Sheeran", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717758/ed-sheeran_hcoiag.webp" },
  { id: 10, title: "Travis Scott", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717768/travis_j1psjr.webp" },
  { id: 11, title: "Sabrina Carpenter", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717764/sabrina_hlyp1p.jpg" },
  { id: 12, title: "Diljit Dosanjh", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717755/diljit_y43y86.jpg" },
  { id: 13, title: "AP Dhillon", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717754/ap_jk7sz3.jpg" },
  { id: 14, title: "Prateek Kuhad", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717762/prateek_yz2xh6.jpg" },
  { id: 15, title: "Anuv Jain", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717753/anuv_phbjt1.jpg" },
  { id: 16, title: "King", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717759/king_tsoraa.jpg" },
  { id: 17, title: "Shreya Ghoshal", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717766/shreya_anegxp.jpg" },
  { id: 18, title: "Ariana Grande", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717758/ariana-grande_tebcue.jpg" },
  { id: 19, title: "Bruno Mars", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717755/bruno-mars_lkzyfo.jpg" },
  { id: 20, title: "Linkin Park", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717760/linkin-park_mymazr.jpg" },
  { id: 21, title: "Justin Bieber", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717758/justin-bieber_hv2epg.jpg" },
  { id: 22, title: "Maroon 5", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717767/maroon-5_kndgjk.jpg" },
  { id: 23, title: "Shakira", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717768/shakira_q3upyw.jpg" },
  { id: 24, title: "Miley Cyrus", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717767/miley_lxddeg.jpg" },
  { id: 25, title: "Imagine Dragons", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717756/imagine_cga81b.jpg" },
  { id: 26, title: "Lana Del Rey", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717759/lana_jwnktu.jpg" },
  { id: 27, title: "Kendrick Lamar", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717771/kendrick-lamar_jxxm2v.jpg" },
  { id: 28, title: "Katy Perry", image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775717759/katy-perry_vhjyqx.jpg" },
];
