export const FestiveTripIdeas = [
  {
    id: 1,
    name: "Varanasi",
    title: "Varanasi, India",
    country: "India",
    countryCode: "in",
    festival: "Diwali – Festival of Lights",
    Highlights: "Ganga Aarti, thousands of diyas & spiritual rituals",
    insight: "Diwali in Varanasi commemorates Lord Rama's triumphant return. The ghats are illuminated with millions of earthen lamps to guide him home, creating a breathtaking celestial reflection on the Ganges.",
    auspiciousDay: "Nov 1",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718275/diwali_trtgol.jpg",
  },
  {
    id: 2,
    name: "Mecca",
    title: "Mecca, Saudi Arabia",
    country: "Saudi Arabia",
    countryCode: "sa",
    festival: "Hajj & Eid al-Adha",
    Highlights: "Spiritual pilgrimage and Kaaba rituals",
    insight: "Hajj is a mandatory spiritual journey that symbolizes universal equality. It represents a profound submission to the divine, bringing together millions of seekers from every corner of the globe.",
    auspiciousDay: "Varies (May/June)",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718278/mecca_tamv55.jpg",
  },
  {
    id: 3,
    name: "Jerusalem",
    title: "Jerusalem, Israel",
    country: "Israel",
    countryCode: "il",
    festival: "Easter & Passover",
    Highlights: "Holy Sepulchre, Western Wall & religious convergence",
    insight: "Jerusalem hosts a profound convergence of Easter and Passover celebrations. It marks the sacred heart of multiple global faiths, where ancient traditions and shared history meet.",
    auspiciousDay: "Varies (March/April)",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718277/jerusalem_oihxca.jpg",
  },
  {
    id: 4,
    name: "Amritsar",
    title: "Amritsar, India",
    country: "India",
    countryCode: "in",
    festival: "Gurpurab",
    Highlights: "Golden Temple illuminations & kirtans",
    insight: "Gurpurab celebrates the birth of Guru Nanak. On this day, the Golden Temple is transformed into a sanctuary of selfless service, peace, and radiant divine light.",
    auspiciousDay: "Nov 25",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718275/amritsar_cyp5dk.jpg",
  },
  {
    id: 5,
    name: "Kathmandu",
    title: "Kathmandu, Nepal",
    country: "Nepal",
    countryCode: "np",
    festival: "Buddha Jayanti",
    Highlights: "Boudhanath prayers, butter lamps & Buddhist energy",
    insight: "Buddha Jayanti honors the birth, enlightenment, and nirvana of Lord Buddha. The majestic Stupas of Swayambhunath and Boudhanath are filled with prayers and the soft glow of butter lamps.",
    auspiciousDay: "May 1",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718277/kathmandu_yiguhm.jpg",
  },
  {
    id: 6,
    name: "Rio de Janeiro",
    title: "Rio de Janeiro, Brazil",
    country: "Brazil",
    countryCode: "br",
    festival: "Christmas + New Year",
    Highlights: "Copacabana fireworks & beachside masses",
    insight: "Rio's New Year is a global spectacle of renewal and joy. Millions of white-clad celebrants gather on Copacabana beach to offer flowers to the sea under a sky of magnificent fireworks.",
    auspiciousDay: "Dec 25",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718285/rio_sa46hq.jpg",
  },
  {
    id: 7,
    name: "Pushkar",
    title: "Pushkar, India",
    country: "India",
    countryCode: "in",
    festival: "Kartik Purnima",
    Highlights: "Cultural fair and spiritual rituals at the lake",
    insight: "Kartik Purnima marks the creation of Pushkar Lake by Lord Brahma. It is a sacred day of spiritual cleansing and vibrant cultural celebration in the heart of the Rajasthan desert.",
    auspiciousDay: "Nov 24",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718281/pushkar_abaonb.jpg",
  },
  {
    id: 8,
    name: "Bangkok",
    title: "Bangkok, Thailand",
    country: "Thailand",
    countryCode: "th",
    festival: "Songkran – Thai New Year",
    Highlights: "Fun water fights and Buddhist temple blessings",
    insight: "Songkran is the traditional Thai New Year. It is a joyful celebration of renewal where water is used to wash away the old and usher in fresh blessings for the coming year.",
    auspiciousDay: "April 13-15",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718290/songkran_poox1w.jpg",
  },
  {
    id: 9,
    name: "Lourdes",
    title: "Lourdes, France",
    country: "France",
    countryCode: "fr",
    festival: "Feast of the Assumption",
    Highlights: "Torchlight processions and healing masses",
    insight: "The Feast of the Assumption is a major day of Catholic pilgrimage. It honors the Virgin Mary and centers around the sacred grotto where miraculous healings and spiritual strength are sought.",
    auspiciousDay: "Aug 15",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718274/assumption-day_icpka2.jpg",
  },
  {
    id: 10,
    name: "Bali",
    title: "Bali, Indonesia",
    country: "Indonesia",
    countryCode: "id",
    festival: "Nyepi – Day of Silence",
    Highlights: "Unique silence rituals and Ogoh-Ogoh parades",
    insight: "Nyepi is Bali's unique Day of Silence. It is a day dedicated to meditation and self-reflection, when the entire island comes to a standstill to cleanse the spirit and restore natural balance.",
    auspiciousDay: "March",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718285/nyepi_dczj6j.jpg",
  },
  {
    id: 11,
    name: "Mexico City",
    title: "Mexico City, Mexico",
    country: "Mexico",
    countryCode: "mx",
    festival: "Day of the Dead",
    Highlights: "Ofrendas, calaveras and soulful remembrance",
    insight: "The Day of the Dead is a beautiful and soulful remembrance. Families use vibrant ofrendas and marigold paths to guide the spirits of their loved ones back for a night of shared celebration.",
    auspiciousDay: "Nov 2",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718300/mexico_q7r2g0.jpg",
  },
  {
    id: 12,
    name: "Kyoto",
    title: "Kyoto, Japan",
    country: "Japan",
    countryCode: "jp",
    festival: "Cherry Blossom (Hanami)",
    Highlights: "Sakura blooms and traditional tea rituals",
    insight: "Hanami is the ancient Japanese tradition of cherry blossom viewing. It celebrates the fleeting beauty of life and the arrival of spring under the breathtaking canopy of Sakura trees.",
    auspiciousDay: "April",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718311/kyoto_ps7smo.jpg",
  },
  {
    id: 13,
    name: "Munich",
    title: "Munich, Germany",
    country: "Germany",
    countryCode: "de",
    festival: "Oktoberfest",
    Highlights: "Bavarian culture, beer tents and parades",
    insight: "Oktoberfest is the world's largest celebration of Bavarian culture. It is a joyful festival that highlights shared community spirit, traditional heritage, and world-renowned hospitality.",
    auspiciousDay: "Sept / Oct",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718286/munich_zrej65.jpg",
  },
  {
    id: 14,
    name: "Venice",
    title: "Venice, Italy",
    country: "Italy",
    countryCode: "it",
    festival: "Venice Carnival",
    Highlights: "Masquerade masks and mysterious elegance",
    insight: "The Venice Carnival is an explosion of mysterious elegance and artistic flair. Iconic masquerade masks allow participants to escape into a temporary world of historical fantasy and beauty.",
    auspiciousDay: "February",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718303/venice_nfivvn.jpg",
  },
  {
    id: 15,
    name: "Seville",
    title: "Seville, Spain",
    country: "Spain",
    countryCode: "es",
    festival: "Semana Santa",
    Highlights: "Intense devotion and processional floats",
    insight: "Semana Santa is an intense and moving display of devotion. Magnificent processional floats move through historic streets, showcasing centuries of tradition and masterful artistry.",
    auspiciousDay: "April",
    image: "https://res.cloudinary.com/dbjgmxt8h/image/upload/q_auto/f_auto/v1775718309/seville_ppeklx.jpg",
  },
];
