export const CITY_TO_IATA: Record<string, string> = {
  Aalborg: "AAL", Aarhus: "AAR", Abadan: "ABD", Abakan: "ABA", Aberdeen: "ABZ",
  Abha: "AHB", "Abu Dhabi": "AUH", Abidjan: "ABJ", Abilene: "ABI", Abuja: "ABV",
  Acapulco: "ACA", Acarigua: "AGV", Accra: "ACC", "Adak Island": "ADK", Adana: "ADA",
  "Addis Ababa": "ADD", Adelaide: "ADL", Aden: "ADE", Adler: "AER", Agadir: "AGA",
  Aguascaliente: "AGU", Ahmedabad: "AMD", Ajaccio: "AJA", Akita: "AXT", "Akron/Canton": "CAK",
  "Al-Baha": "ABT", "Al-Fujairah": "FJR", Albany: "ALB", Albuquerque: "ABQ", Aleppo: "ALP",
  Alexandria: "ESF", Algiers: "ALG", Alicante: "ALC", Allentown: "ABE", "Alma Ata": "ALA",
  "Alor Setar": "AOR", Altoona: "AOO", Amarillo: "AMA", Amman: "AMM", Amritsar: "ATQ",
  Amsterdam: "AMS", Anchorage: "ANC", Ancona: "AOI", Andahuaylas: "ANS", Anguilla: "AZA",
  Aniak: "ANI", Ankara: "ANK", Antalya: "AYT", Antananarivo: "TNR", Antofagasta: "ANF",
  Antwerp: "ANR", Aomori: "AOJ", Apia: "APW", Appleton: "ATW", Aqaba: "AQJ",
  Arequipa: "AQP", Arica: "ARI", Aruba: "AUA", Asheville: "AVL", Asmara: "ASM",
  Asuncion: "ASU", Aswan: "ASW", Athens: "ATH", Atlanta: "ATL", "Atlantic City": "ACY",
  Auckland: "AKL", Augusta: "AGS", Austin: "AUS", Ayacucho: "AYP",
  Baghdad: "BGW", Bahrain: "BAH", Bakersfield: "BFL", "Bali Island": "DPS", Baltimore: "BWI",
  Bamako: "BKO", "Bandar Abbas": "BND", "Bandar Seri Bagawan": "BWN", Bangalore: "BLR",
  Bangkok: "BKK", Bangor: "BGR", Bangui: "BGF", Banjul: "BJL", Barbados: "BGI",
  Barcelona: "BCN", Bari: "BRI", Barinas: "BNS", Barquisimeto: "BRM", Barranquilla: "BAQ",
  Barrow: "BRW", Basle: "BSL", Basra: "BSR", Bastia: "BIA", "Baton Rouge": "BTR",
  Beijing: "BJS", Beira: "BEW", Beirut: "BEY", Belem: "BEL", Belfast: "BFS",
  Belgrade: "BEG", Belize: "BZE", Bellingham: "BLI", "Belo Horizonte": "BHZ",
  Benghazi: "BEN", Bergen: "BGO", Berlin: "BER", Bermuda: "BDA", Bern: "BRN",
  Bethel: "BET", Biak: "BIK", Biarritz: "BIQ", Bilbao: "BIO", Billings: "BIL",
  Billund: "BLL", Birmingham: "BHM", Bissau: "BXO", Blantyre: "BLZ", Bloemfontein: "BFN",
  Bloomington: "BMI", "Boa Vista": "BVB", Bodo: "BOO", Bogota: "BOG", Boise: "BOI",
  Bologna: "BLQ", Bombay: "BOM", Bordeaux: "BOD", Boston: "BOS", Bratislava: "BTS",
  Brazzaville: "BZV", Bremen: "BRE", Brest: "BES", Brisbane: "BNE", Bristol: "BRS",
  Brussels: "BRU", Bucharest: "BUH", Budapest: "BUD", "Buenos Aires": "BUE",
  Cairo: "CAI", Calcutta: "CCU", Calgary: "YYC", Cali: "CLO", Calicut: "CCJ",
  Cancun: "CUN", "Cape Town": "CPT", Caracas: "CCS", Casablanca: "CAS", Cebu: "CEB",
  Chengdu: "CTU", "Chiang Mai": "CNX", Chicago: "CHI", Cincinnati: "CVG", Cleveland: "CLE",
  Cochin: "COK", Cologne: "CGN", Colombo: "CMB", Copenhagen: "CPH", Cork: "ORK",
  Dakar: "DKR", "Dallas/Ft. Worth": "DFW", Damascus: "DAM", "Dar Es Salaam": "DAR",
  Darwin: "DRW", Delhi: "DEL", Denver: "DEN", Detroit: "DTT", Dhahran: "DHA",
  Dhaka: "DAC", Dubai: "DXB", Dublin: "DUB", Dusseldorf: "DUS",
  Edinburgh: "EDI", Edmonton: "YEA", Eindhoven: "EIN",
  Florence: "FLR", Frankfurt: "FRA", Fukuoka: "FUK",
  Geneva: "GVA", Genoa: "GOA", Glasgow: "GLA", Gothenburg: "GOT", Guadalajara: "GDL",
  Guangzhou: "CAN", "Guatemala City": "GUA", Guayaquil: "GYE",
  Halifax: "YHZ", Hamburg: "HAM", Hanoi: "HAN", Hanover: "HAJ", Harare: "HRE",
  Helsinki: "HEL", "Ho Chi Minh City": "SGN", "Hong Kong": "HKG", Honolulu: "HNL",
  Houston: "HOU", Hyderabad: "HYD",
  Indianapolis: "IND", Innsbruck: "INN", Islamabad: "ISB", Istanbul: "IST",
  Jacksonville: "JAX", Jaipur: "JAI", Jakarta: "JKT", Jeddah: "JED", Johannesburg: "JNB",
  Kabul: "KBL", Karachi: "KHI", Kathmandu: "KTM", "Kuala Lumpur": "KUL", Kuwait: "KWI",
  Lagos: "LOS", Lahore: "LHE", "Las Vegas": "LAS", Leipzig: "LEJ", Lima: "LIM",
  Lisbon: "LIS", Liverpool: "LPL", London: "LON", "Los Angeles": "LAX", Luxembourg: "LUX",
  Lyon: "LYS",
  Madras: "MAA", Madrid: "MAD", Malaga: "AGP", Male: "MLE", Manchester: "MAN",
  Manila: "MNL", Marseille: "MRS", Melbourne: "MEL", Memphis: "MEM", "Mexico City": "MEX",
  Milan: "MIL", Minneapolis: "MSP", Montevideo: "MVD", Montreal: "YMQ", Moscow: "MOW",
  Munich: "MUC", Muscat: "MCT",
  Nairobi: "NBO", Naples: "NAP", Nashville: "BNA", Nassau: "NAS", "New York": "NYC",
  Nice: "NCE",
  "Oklahoma City": "OKC", Orlando: "ORL", Osaka: "OSA", Oslo: "OSL", Ottawa: "YOW",
  Palermo: "PMO", Paris: "PAR", Perth: "PER", Philadelphia: "PHL", Phoenix: "PHX",
  Pittsburgh: "PIT", Prague: "PRG",
  Quebec: "YQB",
  Rabat: "RBA", "Rio de Janeiro": "RIO", Riyadh: "RUH", Rome: "ROM",
  Sacramento: "SAC", "Salt Lake City": "SLC", "San Antonio": "SAT", "San Diego": "SAN",
  "San Francisco": "SFO", "San Jose": "SJC", "San Juan": "SJU", Santiago: "SCL",
  "Sao Paulo": "SAO", Seattle: "SEA", Seoul: "SEL", Shanghai: "SHA", Singapore: "SIN",
  "St. Petersburg": "LED", Stockholm: "STO", Stuttgart: "STR", Sydney: "SYD",
  "Tel Aviv Yafo": "TLV", Tokyo: "TYO", Toronto: "YTO", Trivandrum: "TRV",
  Tunis: "TUN", Turin: "TRN",
  Vancouver: "YVR", Venice: "VCE", Vienna: "VIE",
  Warsaw: "WAW", Washington: "WAS", Wellington: "WLG", Winnipeg: "YWG",
  Zurich: "ZRH",
  "New Delhi": "DEL", Mumbai: "BOM", Bengaluru: "BLR", Chennai: "MAA",
  Kolkata: "CCU", Kochi: "COK", Goa: "GOI", Mopa: "GOX",
  Visakhapatnam: "VTZ", Tirupati: "TIR", Vijayawada: "VGA", Rajahmundry: "RJA",
  Kadapa: "CDP", Kurnool: "KJB",
  Itanagar: "HGI", Pasighat: "IXT", Tezu: "TEI",
  Guwahati: "GAU", Dibrugarh: "DIB", Silchar: "IXS", Jorhat: "JRH",
  Tezpur: "TEZ", "North Lakhimpur": "IXI",
  Patna: "PAT", Gaya: "GAY", Darbhanga: "DBR",
  Chandigarh: "IXC",
  Raipur: "RPR", Jagdalpur: "JGB", Bilaspur: "PAB",
  Surat: "STV", Vadodara: "BDQ", Rajkot: "RAJ", Bhavnagar: "BHU",
  Jamnagar: "JGA", Bhuj: "BHJ", Kandla: "IXY", Porbandar: "PBD",
  Hisar: "HSS",
  Kullu: "KUU", Shimla: "SLV", Kangra: "DHM",
  Srinagar: "SXR", Jammu: "IXJ",
  Ranchi: "IXR", Deoghar: "DGH", Jamshedpur: "IXW",
  Mangaluru: "IXE", Hubli: "HBX", Belgaum: "IXG", Mysore: "MYQ", Kalaburagi: "GBI",
  Thiruvananthapuram: "TRV", Kozhikode: "CCJ", Kannur: "CNN",
  Leh: "IXL",
  Indore: "IDR", Bhopal: "BHO", Gwalior: "GWL", Jabalpur: "JLR", Khajuraho: "HJR",
  Pune: "PNQ", Nagpur: "NAG", Nashik: "ISK", Aurangabad: "IXU",
  Shirdi: "SAG", Kolhapur: "KLH", Nanded: "NDC",
  Imphal: "IMF",
  Shillong: "SHL",
  Aizawl: "AJL",
  Dimapur: "DMU",
  Bhubaneswar: "BBI", Jharsuguda: "JSA",
  ATQ_Amritsar: "ATQ", Bathinda: "BUP", Pathankot: "IXP", Ludhiana: "LUH", Jalandhar: "AIP",
  Udaipur: "UDR", Jodhpur: "JDH", Jaisalmer: "JSA", Bikaner: "BKB", Ajmer: "KQH",
  Gangtok: "PYG",
  Coimbatore: "CJB", Madurai: "IXM", Tiruchirappalli: "TRZ", Tuticorin: "TCR", Salem: "SXV",
  Agartala: "IXA",
  Lucknow: "LKO", Varanasi: "VNS", Ayodhya: "AYJ", Kanpur: "KNU", Agra: "AGR",
  Gorakhpur: "GOP", Prayagraj: "IXD", Bareilly: "BEK", Kushinagar: "KJU", Noida: "DXN",
  Dehradun: "DED",
  Bagdogra: "IXB", Siliguri: "IXB",
  "Port Blair": "IXZ", Diu: "DIU", Pondicherry: "PNY", Agatti: "AGX",
};
